### ISSUE TITLE
App crashes when trying to delete past message

### ISSUE THREAD

**Issue by ConnorKirkpatrick** [ConnorKirkpatrick/discord_python_bot#1]
2021-04-21T08:52:03.881310+00:00 app[worker.1]:   File "/app/monitorTimer.py", line 10, in monitorTimer
2021-04-21T08:52:03.881310+00:00 app[worker.1]:     await monitorLoop.getDetails(client)
2021-04-21T08:52:03.881312+00:00 app[worker.1]:   File "/app/monitorLoop.py", line 18, in getDetails
2021-04-21T08:52:03.881312+00:00 app[worker.1]:     await channel.last_message.delete()
2021-04-21T08:52:03.881320+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/discord/message.py", line 1022, in delete
2021-04-21T08:52:03.881321+00:00 app[worker.1]:     await self._state.http.delete_message(self.channel.id, self.id)
2021-04-21T08:52:03.881323+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/discord/http.py", line 250, in request
2021-04-21T08:52:03.881323+00:00 app[worker.1]:     raise NotFound(r, data)
2021-04-21T08:52:03.881339+00:00 app[worker.1]: discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message

Needs a catch to mitigate the error. ensure code keeps running without fatal error

**Comment by ConnorKirkpatrick** [comment]
2021-04-21T10:04:03.769879+00:00 app[worker.1]: Traceback (most recent call last):
2021-04-21T10:04:03.769909+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
2021-04-21T10:04:03.769910+00:00 app[worker.1]:     await coro(*args, **kwargs)
2021-04-21T10:04:03.769912+00:00 app[worker.1]:   File "/app/main.py", line 34, in on_message
2021-04-21T10:04:03.769912+00:00 app[worker.1]:     await monitorTimer.monitorTimer(client)
2021-04-21T10:04:03.769920+00:00 app[worker.1]:   File "/app/monitorTimer.py", line 10, in monitorTimer
2021-04-21T10:04:03.769921+00:00 app[worker.1]:     await monitorLoop.getDetails(client)
2021-04-21T10:04:03.769922+00:00 app[worker.1]:   File "/app/monitorLoop.py", line 18, in getDetails
2021-04-21T10:04:03.769923+00:00 app[worker.1]:     await channel.last_message.delete()
2021-04-21T10:04:03.769933+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/discord/message.py", line 1022, in delete
2021-04-21T10:04:03.769934+00:00 app[worker.1]:     await self._state.http.delete_message(self.channel.id, self.id)
2021-04-21T10:04:03.769936+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/discord/http.py", line 250, in request
2021-04-21T10:04:03.769936+00:00 app[worker.1]:     raise NotFound(r, data)
2021-04-21T10:04:03.769956+00:00 app[worker.1]: discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Full log

**Comment by ConnorKirkpatrick** [comment]
Issue addressed in commit to guilds: 04b63bbe96b53bb84afb2094bd89a6dbd3f7ea96
closing
